-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 18:56:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_siree
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_siree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_siree` DEFAULT CHARACTER SET utf8 ;
USE `db_siree` ;

-- -----------------------------------------------------
-- Table `db_siree`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`ROL` (
  `Id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`USUARIOS` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(15) NOT NULL,
  `id_rol` INT(8) NULL,
  `celular` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `Fk_ROL_USUARIOS_idx` (`id_rol` ASC) ,
  CONSTRAINT `Fk_ROL_USUARIOS`
    FOREIGN KEY (`id_rol`)
    REFERENCES `db_siree`.`ROL` (`Id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`NOTIFICACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`NOTIFICACIONES` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_notificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`RENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`RENTAS` (
  `id_renta` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fecha_renta` DATE NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `precio_total` DECIMAL NOT NULL,
  `id_notificacion` INT NOT NULL,
  PRIMARY KEY (`id_renta`),
  INDEX `fk_renta_usuario_idx` (`id_usuario` ASC) ,
  INDEX `fk_renta_notificacion_idx` (`id_notificacion` ASC) ,
  CONSTRAINT `fk_renta_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_siree`.`USUARIOS` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_renta_notificacion`
    FOREIGN KEY (`id_notificacion`)
    REFERENCES `db_siree`.`NOTIFICACIONES` (`id_notificacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`EQUIPOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`EQUIPOS` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `categoria` VARCHAR(30) NOT NULL,
  `valor_renta` DECIMAL NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  PRIMARY KEY (`id_equipo`))
ENGINE = InnoDB
COMMENT = '					';


-- -----------------------------------------------------
-- Table `db_siree`.`LISTADO_DE_EQUIPOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`LISTADO_DE_EQUIPOS` (
  `Id_listado_equipo` INT NOT NULL AUTO_INCREMENT,
  `id_renta` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `categoria` VARCHAR(30) NOT NULL,
  INDEX `fk_listadodeequipo_renta_idx` (`Id_listado_equipo` ASC) ,
  PRIMARY KEY (`Id_listado_equipo`),
  CONSTRAINT `fk_listadoequipo_renta`
    FOREIGN KEY (`Id_listado_equipo`)
    REFERENCES `db_siree`.`RENTAS` (`id_renta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_listadoquipo_equipo`
    FOREIGN KEY (`Id_listado_equipo`)
    REFERENCES `db_siree`.`EQUIPOS` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
