-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 20:13:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_siree
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_siree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_siree` DEFAULT CHARACTER SET utf8 ;
USE `db_siree` ;

-- -----------------------------------------------------
-- Table `db_siree`.`rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`rentas` (
  `RentaID` INT(11) NOT NULL AUTO_INCREMENT,
  `ClienteID` INT(11) NULL DEFAULT NULL,
  `EquipoID` INT(11) NULL DEFAULT NULL,
  `FechaInicio` DATE NULL DEFAULT NULL,
  `FechaFin` DATE NULL DEFAULT NULL,
  `PrecioTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `EstadoRenta` ENUM('activa', 'completada', 'cancelada') NULL DEFAULT NULL,
  PRIMARY KEY (`RentaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_siree`.`depositos_garantias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`depositos_garantias` (
  `id_transacciones` INT(8) NOT NULL,
  `monto` INT NOT NULL,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`id_transacciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`usuarios` (
  `id_usuarios` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(15) NOT NULL,
  `rol` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`transacciones` (
  `id_usuarios` INT(8) NOT NULL,
  `id_transacciones` INT(8) NOT NULL,
  `id_equipó` INT(8) NOT NULL,
  `fecha_renta` DATE NOT NULL,
  `fecha_devolucion` DATE NULL,
  `estado` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `id_transacciones_UNIQUE` (`id_transacciones` ASC),
  INDEX `id_usuarios_idx` (`id_usuarios` ASC),
  PRIMARY KEY (`id_equipó`),
  CONSTRAINT `id_transacciones`
    FOREIGN KEY (`id_transacciones`)
    REFERENCES `db_siree`.`depositos_garantias` (`id_transacciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `db_siree`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`Equipos` (
  `id_equipos` INT(8) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `categora` VARCHAR(25) NOT NULL,
  `precio_renta` DECIMAL NULL,
  `estado` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_equipos`),
  CONSTRAINT `id_equipo_transacciones`
    FOREIGN KEY (`id_equipos`)
    REFERENCES `db_siree`.`transacciones` (`id_equipó`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_siree`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`notificaciones` (
  `id_notificaciones` INT(8) NOT NULL,
  `id_usuario` INT(8) NULL,
  `mensaje` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `estado` VARCHAR(25) NULL,
  `notificacionescol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_notificaciones`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_siree`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
