-- MySQL Script generated by MySQL Workbench
-- Sat Sep  7 12:05:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_siree
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_siree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_siree` DEFAULT CHARACTER SET utf8 ;
USE `db_siree` ;

-- -----------------------------------------------------
-- Table `db_siree`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`clientes` (
  `ClienteID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Dirección` VARCHAR(255) NULL DEFAULT NULL,
  `Teléfono` VARCHAR(20) NULL DEFAULT NULL,
  `CorreoElectrónico` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ClienteID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_siree`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`equipos` (
  `EquipoID` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreEquipo` VARCHAR(100) NULL DEFAULT NULL,
  `Marca` VARCHAR(50) NULL DEFAULT NULL,
  `Modelo` VARCHAR(50) NULL DEFAULT NULL,
  `NúmeroSerie` VARCHAR(50) NULL DEFAULT NULL,
  `Estado` ENUM('disponible', 'alquilado', 'en mantenimiento') NULL DEFAULT NULL,
  PRIMARY KEY (`EquipoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_siree`.`mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`mantenimiento` (
  `MantenimientoID` INT(11) NOT NULL AUTO_INCREMENT,
  `EquipoID` INT(11) NULL DEFAULT NULL,
  `FechaInicio` DATE NULL DEFAULT NULL,
  `FechaFin` DATE NULL DEFAULT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  `Costo` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`MantenimientoID`),
  INDEX `EquipoID` (`EquipoID` ASC) VISIBLE,
  CONSTRAINT `mantenimiento_ibfk_1`
    FOREIGN KEY (`EquipoID`)
    REFERENCES `db_siree`.`equipos` (`EquipoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_siree`.`rentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`rentas` (
  `RentaID` INT(11) NOT NULL AUTO_INCREMENT,
  `ClienteID` INT(11) NULL DEFAULT NULL,
  `EquipoID` INT(11) NULL DEFAULT NULL,
  `FechaInicio` DATE NULL DEFAULT NULL,
  `FechaFin` DATE NULL DEFAULT NULL,
  `PrecioTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `EstadoRenta` ENUM('activa', 'completada', 'cancelada') NULL DEFAULT NULL,
  PRIMARY KEY (`RentaID`),
  INDEX `ClienteID` (`ClienteID` ASC) VISIBLE,
  INDEX `EquipoID` (`EquipoID` ASC) VISIBLE,
  CONSTRAINT `rentas_ibfk_1`
    FOREIGN KEY (`ClienteID`)
    REFERENCES `db_siree`.`clientes` (`ClienteID`),
  CONSTRAINT `rentas_ibfk_2`
    FOREIGN KEY (`EquipoID`)
    REFERENCES `db_siree`.`equipos` (`EquipoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_siree`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_siree`.`pagos` (
  `PagoID` INT(11) NOT NULL AUTO_INCREMENT,
  `RentaID` INT(11) NULL DEFAULT NULL,
  `FechaPago` DATE NULL DEFAULT NULL,
  `Monto` DECIMAL(10,2) NULL DEFAULT NULL,
  `MétodoPago` ENUM('tarjeta de crédito', 'efectivo', 'transferencia') NULL DEFAULT NULL,
  PRIMARY KEY (`PagoID`),
  INDEX `RentaID` (`RentaID` ASC) VISIBLE,
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`RentaID`)
    REFERENCES `db_siree`.`rentas` (`RentaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
